name: Aula de integração contínua

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: mostra texto
      - run: Echo Aula Ok

      - name: Sincronia com o git
      - uses: kanadgrupta/glitch-sync@v3.0.1
        with:
          auth-token: '${{secrets.authToken}}'
          project-id: '${{secrets.projectId}}'
      
